services:
  app:
    image: ckulka/baikal:0.9.3-nginx
    restart: always
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy

volumes:
  config:
  data:

networks:
  proxy:
    name: nginx-proxy
    external: true
